name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Amazon ECR
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout your repo code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::914964735219:role/open
          aws-region: us-east-1

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Build, Tag, and Push Docker Image to ECR
      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: flask-helloworld        # your repo name in ECR
          IMAGE_TAG: latest
        run: |
          echo "Building Docker image..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Step 5 (optional): Print image URI for confirmation
      - name: Print Image URI
        run: echo "✅ Image pushed:${{ steps.login-ecr.outputs.registry }}/flask-helloworld:latest"

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name poc-demo

      - name: Verify cluster access
        run: kubectl get nodes

      - name: Update image in Kubernetes deployment
        env:
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/flask-helloworld:latest      
        run: |
          echo "Updating image in deployment..."
          kubectl set image deployment/deployment-2048 app-2048=$IMAGE_URI
            -n py-demo-1

      - name: Verify rollout status
        run: |
          kubectl rollout status deployment/deployment-2048 -n py-demo-1

      - name: Confirm updated pods
        run: |
          kubectl get pods -n $K8S_NAMESPACE -o wide
